### ISSUE TITLE
Solution for 'UnityEngine.Networking.UnityWebRequestAsyncOperation' occurred when playing.

### ISSUE THREAD

**Issue by SeokyoungXR** [google/xr-objects#1]
Hi, Thank you for your great work!

When I played on an Android device based on your code, I encountered 'UnityEngine.Networking.UnityWebRequestAsyncOperation'. 
However, I made the following 2 modifications and found that it works fine. 

**1. Changed the google gemini link**
It seems that the gemini url link provided in the existing code was deprecated. I changed it to the link below and that fixed the issue. (I think the gemini-pro-vision API has been deprecated.)

Before:
https://github.com/google/xr-objects/blob/69ed2747c37ac019eb288c4ee137a617613f215f/XRObjects/Assets/XRObjects/Scripts/ImageQuery.cs#L131

After:
`queryURL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key="  + apiKey;`

**2. Android Internet permission in Unity**
Through to in this stackoverflow [link](https://stackoverflow.com/questions/37493936/android-internet-permission-in-unity), I added `<uses-permission android:name=“android.permission.INTERNET”/>` to AndroidManifest.xml (modify the Android AndroidManifest by hand).

After fixing these two things, XR-Object works fine!

Thanks :)

**Comment by dogadogan** [comment]
Dear Seokyoung, thank you very much for your contribution!

You're right, it looks like the Gemini 1.0 Pro Vision has been deprecated on July 12, 2024 ([link](https://stackoverflow.com/a/78999931)). I made a pull request and merged to update it to the new `gemini-1.5-flash` as you suggested!

Merged pull request: https://github.com/google/xr-objects/pull/2


All the best and I look forward to seeing your progress!
