### ISSUE TITLE
Quotation Mark Errors

### ISSUE THREAD

**Issue by Ssstirm** [google/xr-objects#3]
https://github.com/google/xr-objects/blob/fb74bf59cddccad0a696764a717be3c8a1ef9274/XRObjects/Assets/Plugins/Android/AndroidManifest.xml#L8

Hi, thanks for your work! There is a small bug with the quotation.

And after I ran it on my phone, the screen is black with a white, like the image. Is that usual?

![Image](https://github.com/user-attachments/assets/55919a2a-8f5f-4b93-a9f3-c8902bdddaa3)

**Comment by dogadogan** [comment]
Good catch! Just pushed a [fix](https://github.com/google/xr-objects/commit/bff3d4c555d86eef241e2fb655e8b7b99aed0cb1) - does it work now?

For the black screen, can you ensure you enabled the [camera permissions](https://www.lifewire.com/how-to-manage-android-app-permissions-4797758) for the app when it's deployed on your Android phone?

**Comment by Ssstirm** [comment]
> Good catch! Just pushed a [fix](https://github.com/google/xr-objects/commit/bff3d4c555d86eef241e2fb655e8b7b99aed0cb1) - does it work now?
> 
> For the black screen, can you ensure you enabled the [camera permissions](https://www.lifewire.com/how-to-manage-android-app-permissions-4797758) for the app when it's deployed on your Android phone?

I'm sure camera permission is able to the app. Does that UI look correct?

**Comment by dogadogan** [comment]
UI looks right! Can you send a screenshot of the app's permissions list on your phone? Also, what phone do you have?

**Comment by Ssstirm** [comment]
![Image](https://github.com/user-attachments/assets/3ee7fea2-ec25-4917-a1e2-515b7844bccd)

![Image](https://github.com/user-attachments/assets/659d6449-1ad3-49aa-8a9e-f8553d925527)

Here are the screenshots of the permissions and system of my phone

**Comment by dogadogan** [comment]
Is your device listed in [this table](https://developers.google.com/ar/devices#google_play_devices) and does the table mention that it supports Depth API?

**Comment by Ssstirm** [comment]
> Is your device listed in [this table](https://developers.google.com/ar/devices#google_play_devices) and does the table mention that it supports Depth API?

Aha, it's not in the list. Maybe it's the reason

**Comment by Ssstirm** [comment]
BTW, does that support for IOS?

**Comment by dogadogan** [comment]
Right. Feel free to try it on a different phone!

**Comment by dogadogan** [comment]
Right. Feel free to try it on a different phone! I haven't tried it on iOS before, but definitely give it a try. It may work with some little tweaking. You can also refer to the iOS documentation [here](https://github.com/homuler/MediaPipeUnityPlugin), it might be useful while tweaking.

**Comment by Ssstirm** [comment]
I will give a try and let you know afterwards.
